[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.6.1"
hooks = [
  { id = "uv-lock" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.6.3"
hooks = [
  { id = "ruff" },
  { id = "ruff-format" },
]

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer", exclude = '\.json$' },
  { id = "name-tests-test" },
  { id = "check-added-large-files", args = ["--maxkb=15000"] },
]
